version: '3.4'
services:
  validation:
    build: ../
    volumes:
      - ./config:/config
    ports:
      - 8090:8090
    environment:
      SERVER_PORT: "8090"
      DEFAULT_APPLICATION_PROFILE_PATH: "file:/config/applicationProfile.ttl"
    restart: always
